services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - "3306:3306"
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/mysql  # Добавляем volume для хранения данных

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  db_data:  # Определяем volume
